name: Publish to npm

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '>=18.12'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'
          scope: '@medovnik'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: npm run build
      - name: Publish npm
        run: npm publish
      - env:
          NPM_TOKEN: ${{ secrets.NPM_DEPLOY }}
